from argparse import ArgumentParser

import os
import json


def makeParser():
    """Creates a parser for the program parameters

    Returns:
        parser: an ArgumentParser object containing the program parameters
    """
    parser = ArgumentParser(description="Define the program parameters")

    parser.add_argument('-d','--dataset-path', type=str, required=True, 
    help='The location of the dataset.')

    parser.add_argument('-f', '--num-frames-to-label', type=int, nargs='+', required=True,
    help="The number of frames that should be labeled in each AL iteration. Can be a single number or a list.")

    parser.add_argument('-w', '--work-dir', type=str, required=True,
    help="Where to save the outputs for inference and training.")
    
    parser.add_argument('-n', '--custom-name', type=str, required=True,
    help="A custom name for the experiment")
    
    parser.add_argument('-s', '--strategy', type=str, choices=[ # Main methods
                                                                'random',
                                                                'raidal',
                                                                'global-pooled-coreset',
                                                                'soft-attention-coreset',
                                                                'entropy',
                                                                'uncast',

                                                                ## Ablations
                                                                'unfiltered-raidal',
                                                                'raidal-E',
                                                                'raidal-K1',
                                                                'raidal-K2',
                                                                'raidal-K5',
                                                                'raidal-R0',
                                                                'raidal-R2',
                                                                'raidal-R3',
                                                                'raidal-R4',

                                                                ## Additional experiments
                                                                'ctc-badge',
                                                                'raidal-ctc-badge',
                                                                ],
    required=True, help="Whether to use active learning or random sampling.")
    
    parser.add_argument('--device', type=str, required=False, default=0,
    help="What GPU to use during training and inference. Default=0.")

    parser.add_argument('-b', '--bald-iterations', type=int, default=0, required=False,
    help="The number of BALD iterations to run during inference")

    parser.add_argument('--config', '-c', type=str, required=True,
    help="The config file. Should be something like configs/baseline.yaml, or another custom config.")

    parser.add_argument('--checkpoint', type=str, required=False, default=None,
    help="Instead of starting from scratch, loads the labeled.csv, unlabeled.csv and videoRank.json \
    files that were generated by the active learning loop. Just point to the work_dir containing these files.")
    
    parser.add_argument('--use-model', action='store_true', required=False, default=False,
                        help="Like --use-sim-rank, but uses a pretrained model to generate the features and then run selection.")
    
    parser.add_argument('--use-features', nargs=2, metavar=('PATH_TO_LABELED_SET', 'PATH_TO_UNLABELED_SET'), default=None, 
                        help='Uses pregenerated features to make the selection. The fairest way to compare AL strategies.\
                                Takes in two arguments, for example, \'--use-features path/to/labeled/features \
                                path/to/unlabeled/features\'. ALWAYS pass the labeled features first and the unlabeled \
                                features second')

    return parser


def validateParams(args) -> None:
    """validates if the options passed on to the parser are valid

    Args:
        args (an argparse.Namespace object): contains the parameters in a easy to handle object
    """

    for numFrames in args.num_frames_to_label:
        if numFrames <= 0:
            raise ValueError("All elements in num-frames-to-label list must be greater than 0!")
            
    args.num_iterations = len(args.num_frames_to_label)

    if not os.path.exists(args.dataset_path):
        raise FileNotFoundError("-d points to a path that does not exist.")
    
    if not (args.bald_iterations == 0 or args.bald_iterations >= 2):
        raise ValueError("When activated, BALD should run for at least 2 iterations.")

    # Convert args.dataset_path to absolute path and remove trailing "/"
    datasetPath          = args.dataset_path.rstrip("/")
    datasetPath          =  os.path.join(os.getcwd(), datasetPath)
    datasetParentFolder  =  "/".join(datasetPath.split("/")[ : -1])
    datasetName          =  datasetPath.split("/")[-1]
    args.dataset_path    =  datasetPath

    if os.path.exists(f"{datasetParentFolder}/{datasetName}-labeled"):
        raise FileExistsError(f"{datasetParentFolder}/{datasetName}-labeled already exists! Ideally this folder should be created by this program at a later point, meaning \
                              this is probably not your first time running this program. For safety reasons, this program will not continue and I \
                              ask you to deal with this before running the program again :)")

    if os.path.exists(f"{datasetParentFolder}/{datasetName}-unlabeled"):
        raise FileExistsError(f"{datasetParentFolder}/{datasetName}-unlabeled already exists! Ideally this folder should be created by this program at a later point, meaning \
                              this is probably not your first time running this program. For safety reasons, this program will not continue and I \
                              ask you to deal with this before running the program again :)")
    
    if os.path.exists(f"features"):
        raise FileExistsError(f"'features' folder already exists! This could lead to problems when extracting features, please make sure to delete it before running the code :)")

    if args.checkpoint is not None:
        if not os.path.exists(args.checkpoint):
            raise FileNotFoundError(f"Train checkpoint {args.checkpoint} does not exist! Please point to a valid folder!")
        if not os.path.exists(os.path.join(args.checkpoint, "labeled.corpus.csv")):
            raise FileNotFoundError(f"Labeled pool {os.path.join(args.checkpoint, 'labeled.corpus.csv')} does not exist! \
            Please check the chosen folder!")
        if not os.path.exists(os.path.join(args.checkpoint, "unlabeled.corpus.csv")):
            raise FileNotFoundError(f"Unlabeled pool {os.path.join(args.checkpoint, 'unlabeled.corpus.csv')} does not exist! \
            Please check the chosen folder!")
        
        if args.custom_name in args.checkpoint:
            raise Exception(f"Please use a custom name different from the one in the checkpoint. Just to be safe XD.")
            
        if args.use_features is not None:
            if not os.path.exists(args.use_features[0]):
                raise FileNotFoundError(f"Couldn't find {args.use_features[0]}. Make sure it exists!")
            if not os.path.exists(args.use_features[1]):
                raise FileNotFoundError(f"Couldn't find {args.use_features[1]}. Make sure it exists!")

        if args.use_model:
            if not os.path.exists(os.path.join(args.checkpoint, "_best_model.pt")):
                raise Exception

    else:
        if args.use_features is not None:
            raise Exception(f"Can't use --use-features without enabling --args.checkpoint. Please enable it.")
        if args.use_model:
            raise Exception(f"Can't use --use-model without enabling --args.checkpoint. Please enable it.")
        

def saveALParams(args, saveFolder: str) -> None:
    params =    {
                    "num-frames-to-label":   args.num_frames_to_label,
                    "num-runs":              args.num_iterations,
                    "strategy":              args.strategy,
                    "config":                args.config,
                    "bald-iterations":       args.bald_iterations,
                    "checkpoint":            args.checkpoint,
                    "use-model":             args.use_model,
                    "use-features":          args.use_features
                }


    with open(f"{saveFolder}/ALParams.json", "w") as f:
        json.dump(params, f)
